import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";

/**
 * Check if progress file exists
 */
export async function progressExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

/**
 * Read progress file contents
 */
export async function readProgress(path: string): Promise<string> {
  try {
    return await readFile(path, "utf-8");
  } catch {
    return "";
  }
}

/**
 * Append to progress file
 */
export async function appendProgress(
  path: string,
  content: string
): Promise<void> {
  const existing = await readProgress(path);
  const separator = existing.length > 0 ? "\n\n---\n\n" : "";
  await writeFile(path, existing + separator + content, "utf-8");
}

/**
 * Initialize progress file if it doesn't exist
 */
export async function initProgress(path: string): Promise<void> {
  // Ensure parent directory exists (e.g., .ferix/)
  const dir = dirname(path);
  try {
    await mkdir(dir, { recursive: true });
  } catch {
    // Directory may already exist, ignore
  }

  if (!(await progressExists(path))) {
    const header = `# Ferix Progress Log

Generated by Ferix CLI
Started: ${new Date().toISOString()}

---

`;
    await writeFile(path, header, "utf-8");
  }
}
