import { access, mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";

/**
 * Check if progress file exists (internal helper)
 */
async function progressExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

/**
 * Initialize progress file if it doesn't exist
 */
export async function initProgress(path: string): Promise<void> {
  // Ensure parent directory exists (e.g., .ferix/)
  const dir = dirname(path);
  try {
    await mkdir(dir, { recursive: true });
  } catch {
    // Directory may already exist, ignore
  }

  if (!(await progressExists(path))) {
    const header = `# Ferix Progress Log

Generated by Ferix CLI
Started: ${new Date().toISOString()}

---

`;
    await writeFile(path, header, "utf-8");
  }
}
